CREATE TABLE IF NOT EXISTS `acrit_perfmon_run_history` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` datetime NOT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  `SUMMARY` varchar(255) NOT NULL,
  `REPORT_TEXT` mediumtext NOT NULL,
  `TOTAL_COUNT` int(11) NOT NULL DEFAULT 0,
  `SUCCESS_COUNT` int(11) NOT NULL DEFAULT 0,
  `FAIL_COUNT` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `IX_APRH_CREATED_AT` (`CREATED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
